name: Daily ETF Scraper - 8PM

on:
  schedule:
    # 每天 UTC 12:00 執行（台北時間 20:00）
    - cron: '0 12 * * *'
  workflow_dispatch: # 允許手動觸發

jobs:
  trigger-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Railway Scraper
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SCHEDULER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"source": "github-actions", "timezone": "Asia/Taipei", "scheduled_time": "20:00"}' \
            ${{ secrets.RAILWAY_SERVICE_URL }}/trigger-scrape
        
      - name: Check Scraper Result
        run: |
          echo "等待爬蟲執行完成..."
          sleep 30
          
          # 檢查健康狀態
          curl -s ${{ secrets.RAILWAY_SERVICE_URL }}/health | jq '.'
        
      - name: Notify on Failure
        if: failure()
        run: |
          echo "爬蟲執行失敗！請檢查 Railway 日誌"
          echo "時間: $(date)"
          echo "Service URL: ${{ secrets.RAILWAY_SERVICE_URL }}"
